### ISSUE TITLE
Undefined variable found in MoCache.php

### ISSUE THREAD

**Issue by ahmed-sigmalux** [inpsyde/translation-cache#2] opened 2017-09-20 03:04 UTC
I'm running WordPress 4.8.1 with Memcached for object caching. When I enable Translation Cache, I see this warning hundreds of times in my debug.log:

```
[20-Sep-2017 02:46:54 UTC] PHP Notice:  Undefined variable: found in /mnt/disks/www/wordpress/wp-content/plugins/translation-cache/src/MoCache.php on line 339
[20-Sep-2017 02:46:54 UTC] PHP Notice:  Undefined variable: found in /mnt/disks/www/wordpress/wp-content/plugins/translation-cache/src/MoCache.php on line 340
```

Any idea what's going on here?

**Comment by gmazzap** [comment] 2017-09-20 06:51
Hi @ahmed-sigmalux, thanks for reporting.

The issue is probably caused by some object cache dropin that defines `wp_cache_get()` without `$found` or without assigning it be reference.

But I'm going to fix this.

**Comment by gmazzap** [comment] 2017-09-20 06:54
@ahmed-sigmalux The issue should be fixed in master branch. Could you give it a test before I do the release?

**Comment by ahmed-sigmalux** [comment] 2017-09-20 07:09
Yes, that fixed the problem.

Thanks!

**Closed as completed** 2017-09-20 08:23 UTC
Labels: bug
